apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "30m"
spec:
  tls:
  - hosts:
    - {{ .Values.Fqdn }}
    secretName: example-tls
  rules:
  - host: {{ .Values.Fqdn }}
    http:
      paths:
      - path: /
        backend:
          serviceName: example
          servicePort: 80
