apiVersion: v1
kind: Secret
metadata:
  name: container-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.Registry.Endpoint (printf "%s:%s" .Values.Registry.Username .Values.Registry.Password | b64enc) | b64enc }}
